import Navigation from "@/components/Navigation";
import Section from "@/components/Section";
import { flexBasis } from "@/constants";
import { Box, BoxProps, Divider, Link, Typography, styled } from "@mui/joy";
import Head from "next/head";
import { Typewriter } from "react-simple-typewriter";
import Home from "./home/Home";

export default function OnePager() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main style={{ display: 'flex', flexDirection: 'column' }}>
        <Home />
        <Divider />
      </main>
    </>
  );
}
