import Head from 'next/head'
import Home from './Home'
import Contact from './Contact'
import About from './About'
import { Box, IconButton, Typography, useColorScheme } from '@mui/joy'
import { Typewriter } from 'react-simple-typewriter'
import { CloseSharp, Email, Instagram, LinkedIn, MenuSharp } from '@mui/icons-material'
import ThemeToggle from '@/components/themeToggle'

import localFont from 'next/font/local';
import { useState } from 'react'

export const overusedGroteskMedium = localFont({ src: '../../public/fonts/OverusedGrotesk-Medium.ttf' })

function Navigation() {

  const [open, setOpen] = useState(false);

  return (
    <>
      <IconButton sx={{ position: 'absolute', top: open ? '-50rem' : '3rem', right: '3rem', padding: 2, transition: 'top 1s, padding 0.25s, margin 0.25s', borderRadius: 99, backgroundColor: 'background.body', '&:hover': { backgroundColor: 'background.level2', padding: 1.5, margin: 0.5, } }} size='lg' onClick={() => setOpen(true)}>
        <MenuSharp />
      </IconButton>
      <Box sx={{
        position: "absolute",
        top: open ? '3rem' : '-50rem',
        transition: 'top 1s',
        right: '3rem',
        width: '8rem',
        backgroundColor: 'background.surface',
        paddingX: 2,
        paddingY: 1,
        borderRadius: 5
      }}>
        <IconButton sx={{ position: 'absolute', right: 8 }} onClick={() => setOpen(false)}>
          <CloseSharp />
        </IconButton>
        {
          ['Home', 'About', 'Projects', 'Contact'].map((e, i) => (
            <Typography level="body-lg" sx={{
              fontFamily: overusedGroteskMedium, fontWeight: 500, lineHeight: 1.8, fontSize: '1.25rem', transition: '0.25s',
              '&:hover': {
                paddingLeft: '1rem'
              }
            }} key={i}>
              {e}
            </Typography>
          ))
        }
      </Box>
    </>
  )
}


export default function OnePager({ setColorScheme }: { setColorScheme: Function }) {
  return (
    <>
      <Head>
        <title>Ankush Ahuja - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'row' }}>
        <Navigation />
        <Box sx={{
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', minWidth: '4rem', paddingY: 1.5, borderRightWidth: '2px', borderRightColor: 'background.level2', borderRightStyle: 'solid', position: 'sticky'
        }}>
          <Box sx={{
            justifySelf: 'flex-start',
            flexGrow: 1
          }}>
            <ThemeToggle setColorScheme={setColorScheme} />
          </Box>
          {
            [{ icon: <LinkedIn />, link: '' }, { icon: <Instagram />, link: '' }, { icon: <Email />, link: '' }].map((e, i) => (
              <IconButton key={i} size={'sm'} sx={{ borderRadius: 999, padding: 0.5, margin: 'auto', marginY: 0.35 }}>
                {e.icon}
              </IconButton>
            ))
          }
        </Box>
        <Box sx={{ overflowY: 'auto', width: 'calc(100vw - 4rem)'}}>
          <Home />
          <About />
          <Contact />
        </Box>
      </Box>
    </>
  )
}
